### ISSUE TITLE
Mismatch Reconnection policy in the README.MD and com.englishtown.vertx.cassandra.impl.JsonCassandraConfigurator

### ISSUE THREAD

**Issue by cmuxiaodong** [ef-labs/vertx-cassandra#14]
Both Master and Develop branches:
In the JsonCassandraConfigurator, it is loading the Reconnection policy by looking for the json node: "reconnection". 

And the sample config.json specifies it as "reconnect_policy".

**Comment by adrianluisgonzalez** [comment]
Thanks for the PR @potatopankakes
