### ISSUE TITLE
vertx-3.3.0

### ISSUE THREAD

**Issue by jtruelove** [ef-labs/vertx-cassandra#16]
Would you mind cutting a build of the core lib and mapper against vertx-3.3.0-SNAPSHOT? I'm guessing it should have no impact on the library really. I checked the central repo and didn't see it, if you're busy i can submit a pull request for it. Thanks!

**Comment by jtruelove** [comment]
created a pull request here https://github.com/englishtown/vertx-cassandra/pull/17

**Comment by adrianluisgonzalez** [comment]
Released vertx-cassandra 3.4.0 which uses vert.x 3.3.0
